### ISSUE TITLE
Create a UI design for the website

### ISSUE THREAD

**Issue by unnikrishnan2002** [unnikrishnan2002/Narrow-Links#20]
The current design of the app looks kinda simple. Create a new design for the app (You don't have to write code for it, just provide a nice design using figma or any other tool you're comfortable with)

You can share your designs in the comments and I will select on from them

**Comment by cyric2020** [comment]
Just drew up some quick designs in Figma, might be a base for someone else to add to 😄.
If you want to see a different primary colour let me know.

_Square design_
![image](https://user-images.githubusercontent.com/60243062/195591926-7ab10631-b4d0-420e-8d33-f8ec81294b7c.png)
![image](https://user-images.githubusercontent.com/60243062/195591953-39f3d05e-7721-4572-bc99-e85af22265dd.png)

_Rounded design_
![image](https://user-images.githubusercontent.com/60243062/195592038-6ffb1ee2-566e-4f42-b976-228068281593.png)
![image](https://user-images.githubusercontent.com/60243062/195592061-9f82ca28-8343-40d7-81e2-9b4abb0d9fee.png)

**Comment by unnikrishnan2002** [comment]
Hey @cyric2020 can you use some more colors and make it a bit more attractive ? It looks simple with a  white/offwhite background

**Comment by 404-Terror** [comment]
> The current design of the app looks kinda simple. Create a new design for the app (You don't have to write code for it, just provide a nice design using figma or any other tool you're comfortable with)
> 
> You can share your designs in the comments and I will select on from them

Hey can I work on it under hacktoberfest..

**Comment by 404-Terror** [comment]
Here are my designs..

![PR](https://user-images.githubusercontent.com/74364025/195881378-9a617f9a-25c8-4648-8685-652e10426659.png)
![PR (1)](https://user-images.githubusercontent.com/74364025/195881372-70163baf-208b-4f95-b281-8f41417f29f5.png)

**Comment by 404-Terror** [comment]
Here are my designs...

![PR](https://user-images.githubusercontent.com/74364025/195881794-9b06e2cb-1656-4cae-94e7-075cc00121cb.png)
![PR (1)](https://user-images.githubusercontent.com/74364025/195881819-f07a234f-95b3-4ea9-9c53-c329d37cb3e5.png)

**Comment by gnwncpta** [comment]
### Hi 🖐, I came up with this design idea, style & layout.
After trying **NarrowLinks** app and got the understanding of the flow now i can show you my design that i made for **NarrowLinks**.
I also made responsive design for mobile so we together may have the imaginary of how if the app on mobile phone looks like. I also made simple logo for the app so because users will have the identity that will stick on their mind.

So here's the design and with some explanation:

**Link:** [Figma Design](https://www.figma.com/file/GGkebbJ4rTDfgFGNgXd2r4/Narrow-Links?node-id=0%3A1)

### **♦ Idle State**
<img src="https://i.imgur.com/8bcpxMP.png" />

### **📮 Explanation:** 
When the user is the first time opening the app on desktop it will look like this. Okay, you might be asking why the login button have the **auth0** icon, right ? It's because we have to give user an information that the login is just for **auth0** authentication, not for user to manage their links that they made before. You got it ? okay good.


<br/>
<br/>

### **♦ Creating URL State**
<img src="https://i.imgur.com/GC0Pzwd.png" />

### **📮 Explanation:** 
There's not much different from before, It's just when the user paste their link and click Shorten purple button, The app will give the user an information that the links is being generated at the moment.


<br/>
<br/>

### **♦ Result State**
<img src="https://i.imgur.com/Smc5lMm.png" />

### **📮 Explanation:** 
After the generated process is done, then the app will give the shortened url to the user. 
Okay you might be asking again, why i grouping the shortened link and the share buttons like that ? It's because the shortened link and the buttons have a connection between them. So when you see the result like that the user will think that the shortened link is shareable via SMS and QR code. That's it

Why the Show QR button have purple color ? So when user's cursor is hovering on the buttons, the button background color will change to purple color.



### So yeah thats the design that i made 😁
If you have any thoughts or any question you can tell me, Thanks
If you don't mind, let me do the front end work because i know about the design and i can do layouting.

**Comment by unnikrishnan2002** [comment]
@404-Terror I have seen a similar design like this in someone else's project so it would be not right to use this design

Great effort btw 👍

**Comment by unnikrishnan2002** [comment]
@gnwncpta Great design buddy, I really liked it . I would like to take on this design. And yes you can work on the UI if you are willing to

**Comment by unnikrishnan2002** [comment]
@gnwncpta can you please add all these screenshots in a folder named `UI Design` so that we can close the PR for this issue

**Comment by gnwncpta** [comment]
@unnikrishnan2002 Thanks for the feedback 😁, sure i would put the figma link on the README file

**Comment by unnikrishnan2002** [comment]
@gnwncpta Lets get to the UI redesigning part. I am thinking of splitting the UI into two parts. Navbar and the home main home section. You can take up the Home section which is all the part below the navbar and the Navbar redesigning we can assign it to someone else so that everyone gets opportunity. Does that sound good ?

**Comment by gnwncpta** [comment]
Yeah, that's sounds fair enough ✨
