### ISSUE TITLE
Keep the Icons in the navbar visible 

### ISSUE THREAD

**Issue by unnikrishnan2002** [unnikrishnan2002/Narrow-Links#27]
Currently, the icons in the navbar like the Home icon, Github icon, etc appear on hover. We need to remove the hover and keep the icons on display always.

**Comment by najeebkp** [comment]
Hi @unnikrishnan2002 please assign this to me

**Comment by yogesh-9999** [comment]
Hey @najeebkp  assign me

**Comment by Divyesh1511** [comment]
Hey @unnikrishnan2002 please assign me this task, I am currently working on a similar type of project.

**Comment by Divyesh1511** [comment]
hey @unnikrishnan2002, I have solved the issue and attaching that screenshot of the site please check whether it solved the problem or not.
And if it's solved please reply to me so that I can commit the changes
![Screenshot (765)](https://user-images.githubusercontent.com/75933218/195762629-6f5aeec8-c4af-4dc6-a4ab-dd466aa88f89.png)

**Comment by unnikrishnan2002** [comment]
Sorry @Divyesh1511 Your have got it right but someone else commented first and hence I will assign him. But Don't worry , I have got one more similar issue . I can assign it to you if you want

**Comment by unnikrishnan2002** [comment]
Go ahead @najeebkp

**Comment by Divyesh1511** [comment]
Sure @unnikrishnan2002 you can assign me the new issue

**Comment by unnikrishnan2002** [comment]
> Sure @unnikrishnan2002 you can assign me the new issue

#28 Comment on the issue , I will assign you
